### ISSUE TITLE
Built-in types do not vary in size

### ISSUE THREAD

**Issue by rawling** [Wintellect/Wintellect.Analyzers#1]
> **AvoidPredefinedTypes**

> The predefined types, such as int, should not be used. When defining a type the built in types can be different sizes on different versions of .NET (e.g., desktop and Internet of Things) so you want to be as explicit about types as possible. "

This is incorrect. See section 4.1.4 of the C# specification.

> C# provides a set of predefined struct types called the simple types. The simple types are identified through reserved words, but these reserved words are simply aliases for predefined struct types in the System namespace, as described in the table below.

Reserved word|Aliased type
----|---
sbyte|System.SByte
byte|System.Byte
short|System.Int16
ushort|System.UInt16
int|System.Int32
uint|System.UInt32
long|System.Int64
ulong|System.UInt64
char|System.Char
float|System.Single
double|System.Double
bool|System.Boolean
decimal|System.Decimal

**Comment by JohnWintellect** [comment]
Yes, you are right. Sorry about that. All fixed now.
