### ISSUE TITLE
MissingAnalyzerReference warning

### ISSUE THREAD

**Issue by donid** [Wintellect/Wintellect.Analyzers#5]
Hi,
I have created a fresh Win10 VM with VS2015 (from Azure catalog) and then created an empty C# console-project, added the Wintellect.Analyzers with nuget and built it.
The following warning appeared in the "Error List"-Window:

Warning	MissingAnalyzerReference	Analyzer assembly 'c:\users\fk\documents\visual studio 2015\Projects\ConsoleApplication1\packages\Wintellect.Analyzers.1.0.0.0\analyzers\dotnet\cs\Wintellect.Analyzers.Test.dll' depends on 'Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' but it was not found. Analyzers may not run correctly.

**Comment by JohnWintellect** [comment]
Thanks, donid. I was accidentally including extra files in the nuget package. Update the package to get 1.0.1.0 and you'll be set. Appreciate the report.
